ReplicaCount: 1
GithubRepo: ""
GithubTeam: ""
Namespace: ""
Alerts:
  enabled: false
  severity: "data-platform-application-migration-alerts"
  cpuUsage: "60"
  memoryUsage: "80"
  pvcUsage: "90"
WebApp:
  Name: ""
  BaseHost: "apps.live.cloud-platform.service.justice.gov.uk"
  containerPort: 9999
  HealthCheck:
    readinessProbe:
      path: "/?healthz"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 60
    livenessProbe:
      path: "/?healthz"
      initialDelaySeconds: 180
      periodSeconds: 10
      timeoutSeconds: 60
  AlternativeHealthCheck:
    enabled: false
    port: 7999
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 180
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 60
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 180
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 60
  resources:
    requests:
      memory: "1Gi"
      cpu: "125m"
    limits:
      memory: "1Gi"
      cpu: "300m"
  Image:
    Repository: ""
    Tag: ""
    PullPolicy: "IfNotPresent"
Secrets:
  Auth0:
    ClientSecret: ""
    ClientId: ""
  WebApp:
    Parameters: {}
Ingress:
  Port: 80
  Paths:
    - /
  ModSec:
    Enabled: false
  Headers:
    SameOrigin: false
  ExtraAnnotations: {}
ServiceAccount:
  RoleARN: ""
Cron:
  schedule: ""
  image:
    repository: "ghcr.io/ministryofjustice/analytical-platform-kubectl"
    tag: "1.4.0"
  securityContext:
    runAsUser: 10000