{{ if .Values.Ingress.Enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "stripPrefixSuffixFromName" . }}
  annotations:
  {{ if .Values.Ingress.ModSec.Enabled }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log{{ if .Values.GithubTeam }},tag:github_team={{ .Values.GithubTeam }}{{ end }}"
  {{ end }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: deny";
      {{ if .Values.Ingress.Headers.SameOrigin }}
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      {{ end }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ template "stripPrefixSuffixFromName" . }}-{{ .Values.Namespace }}-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  {{- with .Values.Ingress.ExtraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.Ingress.ModSec.Enabled }}
  ingressClassName: modsec
  {{ else }}
  ingressClassName: default
  {{ end }}
  tls:
    - hosts:
        - {{ template "stripPrefixSuffix" . }}
  rules:
    - host: {{ template "stripPrefixSuffix" . }}
      http:
        paths:
        {{- if kindIs "slice" .Values.Ingress.Paths }}
          {{- range .Values.Ingress.Paths }}
            - pathType: ImplementationSpecific
              path: {{ . | quote }}
              backend:
                service:
                  name: {{ $.Values.WebApp.Name }}
                  port:
                    number: {{ $.Values.Ingress.Port }}
          {{- end }}
        {{- else if .Values.Ingress.Path }}
            - pathType: ImplementationSpecific
              path: {{ .Values.Ingress.Path | quote }}
              backend:
                service:
                  name: {{ $.Values.WebApp.Name }}
                  port:
                    number: {{ $.Values.Ingress.Port }}
        {{- else }}
            - pathType: ImplementationSpecific
              path: "/"
              backend:
                service:
                  name: {{ $.Values.WebApp.Name }}
                  port:
                    number: {{ $.Values.Ingress.Port }}
        {{- end }}
{{ end }}
