apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.WebApp.Name }}
spec:
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: {{ .Values.Ingress.Port }}
    protocol: TCP
    targetPort: {{ .Values.WebApp.containerPort }}
  selector:
    app: {{ .Values.WebApp.Name }}
