apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.WebApp.Name }}
spec:
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.Ingress.Port }}
      targetPort: {{ .Values.WebApp.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.WebApp.Name }}
